INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Javi Guerra', '39', 'España', '5');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Hugo Duro', '39', 'España', '2');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Griezzman', '40', 'Francia', '3');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Bellingham', '41', 'Inglaterra', '5');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Lewandowski', '42', 'Polonia', '8');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Guruzeta', '43', 'España', '6');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Chimy Avila', '44', 'España', '2');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Muriqi', '45', 'Kosovo', '1');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Jonathan Viera', '46', 'España', '1');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Ruben Sobrino', '47', 'España', '5');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Rafa Mir', '48', 'España', '8');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Isco', '49', 'España', '4');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Luis suarez', '50', 'Colombia', '2');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Bryan Zaragoza', '51', 'Española', '8');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Gerard Moreno', '52', 'España', '7');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Eres Ünal', '53', 'Turquia', '8');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('R.D.T.', '54', 'España', '4');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Iago Aspas', '55', 'España', '3');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Oyarzabal', '56', 'España', '4');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Hagi', '57', 'Rumania', '6');
INSERT INTO `laliga`.`jugadores` (`nombre`, `idequipo`, `nacionalidad`, `goles`) VALUES ('Stuani', '58', 'Uruguay', '5');
